version: "2"

services:
  github-project-boards-backup:
    build: .
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - GITHUB_USER
      - TOKEN=${GITHUB_ACCESS_TOKEN}
      - MAX_BACKUPS=10
      - TIME_ZONE=America/Chicago
    volumes:
      - ./var:/srv/var